name: Cypress E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run Cypress tests (headless)
      - name: Run Cypress tests
        run: npx cypress run --browser chrome
        env:
          CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
          CYPRESS_EMAIL_PASSWORD: ${{ secrets.CYPRESS_EMAIL_PASSWORD }}

      # 5. Upload screenshots on failure (this optional but recommended)
      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # 6. Upload videos (optional)
      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

      # 7. Generate a brief test summary
      - name: Test Summary
        if: always()
        run: |
          echo "Cypress test run completed"
          echo "Check logs above for pass/fail details"
